spring.application.name=myweb4

# 포트설정
server.port=80

# DB설정
spring.datasource.url=jdbc:mysql://localhost:3306/studydb
spring.datasource.username=root
spring.datasource.password=mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ViewResolver
spring.mvc.view.prefix=/WEB-INF/
spring.mvc.view.suffix=.jsp

# Loggin??
# 전체 로그레벨 :  TRACE < DEBUG < INFO < WARN < ERROR
logging.level.root=INFO
# 해당패키지 로그레벵
logging.level.com.spring.myweb1.biz=INFO

# multipart : Spring boot는 Multipart를 내장하고 있다.
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true 


# @Value("${file.upload-dir}")로 호출해서 사용할수 있다.
file.upload-dir=C:/test/